// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkMhYWkxN8AfLkUMjuUuWAJVh6UsCXiVs',
    appId: '1:237698448890:web:fda77557f15a0ae150b843',
    messagingSenderId: '237698448890',
    projectId: 'fir-demo-mac',
    authDomain: 'fir-demo-mac.firebaseapp.com',
    storageBucket: 'fir-demo-mac.firebasestorage.app',
    measurementId: 'G-6Y0SYJX8C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-iku8XtLKO-uuZZvAluo4-CIFczPp1js',
    appId: '1:237698448890:android:f8b32ef202ba1d8150b843',
    messagingSenderId: '237698448890',
    projectId: 'fir-demo-mac',
    storageBucket: 'fir-demo-mac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd8MzcF1YYFImH3cXQofWqNii_zJVzYjA',
    appId: '1:237698448890:ios:32fdaf4954c7ee8850b843',
    messagingSenderId: '237698448890',
    projectId: 'fir-demo-mac',
    storageBucket: 'fir-demo-mac.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd8MzcF1YYFImH3cXQofWqNii_zJVzYjA',
    appId: '1:237698448890:ios:32fdaf4954c7ee8850b843',
    messagingSenderId: '237698448890',
    projectId: 'fir-demo-mac',
    storageBucket: 'fir-demo-mac.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkMhYWkxN8AfLkUMjuUuWAJVh6UsCXiVs',
    appId: '1:237698448890:web:7f1f5426731258f750b843',
    messagingSenderId: '237698448890',
    projectId: 'fir-demo-mac',
    authDomain: 'fir-demo-mac.firebaseapp.com',
    storageBucket: 'fir-demo-mac.firebasestorage.app',
    measurementId: 'G-G4F35LPKJ8',
  );
}
